# Функциональное программирование на Python

1. [Итерируемые объекты](#iter)
2. [Генераторы и итераторы](#gen)
3. [Принцип работы for](#for)
4. [Объект range](#range)
5. [Генераторы itertools](#itertools)
6. [Сопроцессы](#Coprocesses)
7. [Работа с файлами](#files)

## 1. Итерируемые объекты <a name="iter"></a>

### Списки

In [1]:
empty_list = list()
empty_list

[]

In [2]:
empty_list = []
empty_list

[]

In [3]:
my_list = [1, 'some', 3.5]
my_list

[1, 'some', 3.5]

In [4]:
my_list = list(idx for idx in range(3))
my_list

[0, 1, 2]

#### Базовые операции со списками

#### Замена элементов

In [5]:
my_list[1] = 11
my_list

[0, 11, 2]

In [6]:
my_list[10] = 22

IndexError: list assignment index out of range

#### Удаление элементов

In [7]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [8]:
del my_list[0]
my_list

[2, 3, 4, 5]

In [9]:
del my_list[:2] 
my_list

[4, 5]

In [10]:
del my_list[:]
my_list

[]

#### Сравнение

In [11]:
a = [3, 20, 1]
b = [10, 2, 3]

In [12]:
a == b

False

In [13]:
a != b

True

In [14]:
a > b

False

При удалении списка (например, с помощью del, или сборщика мусора), его опустошенный объект кешируется и используется в последующем для создания нового списка.

In [ ]:
list_0 = [1, 2, 3]
print('list_0 %s' % id(list_0))  # list_0 139904656455656
del list_0

In [ ]:
list_1 = []
print('list_1 %s' % id(list_1))  # list_1 139904656455656
del list_1

In [ ]:
list_2 = [4, 5]
print('list_2 %s' % id(list_2))  # list_2 139904656455656
list_2.extend([6, 7])

In [ ]:
list_3 = []
print('list_3 %s' % id(list_3))  # list_3 139904656456952
del list_3

In [ ]:
list_4 = []
print('list_4 %s' % id(list_4))  # list_4 139904656456952

### Строки

In [15]:
a = str(10)
a

'10'

In [16]:
str(len)

'<built-in function len>'

### TUPLE (КОРТЕЖ)

In [17]:
my_empty_tuple = ()

In [18]:
my_tuple = 1, 'some', 3.5
my_tuple

(1, 'some', 3.5)

In [19]:
my_tuple = 'a',
my_tuple

('a',)

In [20]:
type(my_tuple)

tuple

In [21]:
a = tuple('abc')
a

('a', 'b', 'c')

In [22]:
b = tuple([1, 2, 3])
b

(1, 2, 3)

In [23]:
a == b

False

#### Сравнения

In [24]:
a = (3, 2, 1)
b = (1, 2, 3)
d = (3, 2, 2)
e = (3, 2)
f = (3, 2, 'a')

In [25]:
a > b

True

In [26]:
a > d

False

In [27]:
d > b

True

In [28]:
a > e

True

In [29]:
a > f # False for Python 2

TypeError: '>' not supported between instances of 'int' and 'str'

In [30]:
a = ()
b = ()
a is b

True

In [31]:
id(a) == id(b)

True

## Словари

In [32]:
my_dict = {
    'key': 'value', 
    'sub_dict': {},
    2: [1, 2, 3, 4], 
}

In [33]:
my_dict

{'key': 'value', 'sub_dict': {}, 2: [1, 2, 3, 4]}

In [ ]:
# Словарь из итерирующегося объекта.
my_dict = dict(zip(['one', 'two', 'three'], [1, 2, 3])) 

In [ ]:
# Словарь из именованных аргументов.
my_dict = dict(one=1, two=2, three=3)

In [ ]:
# Словарь из списка кортежей.
my_dict = dict([('two', 2), ('one', 1), ('three', 3)])

## 2. Генераторы и итераторы <a name="gen"></a>

Итератор представляет собой объект перечислитель, который для данного объекта выдает следующий элемент, а случае если следующих элементов нет, то бросает исключение.

In [34]:
num_list = [1, 2, 3, 4, 5]
for i in num_list:
    print(i, end=' ')

1 2 3 4 5 

In [35]:
itr = iter(num_list)
print(next(itr))

1


In [36]:
print(next(itr))

2


Если нужно обойти элементы внутри объекта вашего собственного класса, необходимо построить свой итератор. Создадим класс, объект которого будет итератором, выдающим определенное количество единиц, которое пользователь задает при создании объекта. Такой класс будет содержать конструктор, принимающий на вход количество единиц и метод __next__(), без него экземпляры данного класса не будут итераторами.

In [37]:
class SimpleIterator:
    def __init__(self, limit):
        self.limit = limit
        self.counter = 0

    def __next__(self):
        if self.counter < self.limit:
            self.counter += 1
            return 1
        else:
            raise StopIteration

In [38]:
s_iter1 = SimpleIterator(3)
print(next(s_iter1))

1


In [39]:
print(next(s_iter1))

1


Если мы хотим, чтобы с данным объектом можно было работать в цикле for, то в класс SimpleIterator нужно добавить метод __iter__(), который возвращает итератор, в данном случае этот метод должен возвращать self.

In [40]:
class SimpleIterator:
    def __iter__(self):
        return self

    def __init__(self, limit):
        self.limit = limit
        self.counter = 0

    def __next__(self):
        if self.counter < self.limit:
            self.counter += 1
            return 1
        else:
            raise StopIteration



In [41]:
s_iter2 = SimpleIterator(5)
for i in s_iter2:
    print(i, end=' ')

1 1 1 1 1 

Генератор – это функция, которая будучи вызванной в функции next() возвращает следующий объект согласно алгоритму ее работы. Вместо ключевого слова return в генераторе используется yield.

## 3. Принцип работы for <a name="for"></a>

In [42]:
for i in 1, 2, 'one', 'two':
    print(i)

1
2
one
two


In [43]:
squares_1 = []
for i in range(10):
    squares_1.append(i * i)

squares_1

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

### List Comprehensions

In [44]:
squares_2 = [i * i for i in range(10)]
squares_2

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [45]:
for i in range(len(squares_2)):
    print(squares_2[i], end=' ')

0 1 4 9 16 25 36 49 64 81 

## 4. Объект range<a name="range"></a>

range(Start, Stop[, Step])

In [46]:
r_1 = range(10)
r_1

range(0, 10)

In [47]:
for it in r_1:
    print(it, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [48]:
range(1.1)

TypeError: 'float' object cannot be interpreted as an integer

In [49]:
range(1, 10, 0)

ValueError: range() arg 3 must not be zero

In [50]:
start = 1
stop = 6.7
step = 0.1
for value in range(start, stop, step):
    print (value)

TypeError: 'float' object cannot be interpreted as an integer

### Функция NumPy Arange() для диапазона значений с плавающей запятой

In [51]:
start = 1
stop = 6.7
step = 0.1

In [52]:
import numpy as np

np.arange(start, stop, step)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6])

In [53]:
from numpy import arange

print("Float range using NumPy arange():")

print("\nTest 1:")
for i in arange(0.0, 10.0, 0.5):
    print(i, end=', ')

print("\n\nTest 2:")
for i in arange(0.5, 5.5, 0.5):
    print(i, end=', ')

print("\n\nTest 3:")
for i in arange(-1.0, 1.0, 0.5):
    print(i, end=', ')

Float range using NumPy arange():

Test 1:
0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 

Test 2:
0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 

Test 3:
-1.0, -0.5, 0.0, 0.5, 

### Функция NumPy Linspace для генерации диапазона с плавающей запятой

linspace(start, stop, num, endpoint)

start => starting point of the range

stop => ending point

num => Number of values to generate, non-negative, default value is 50.

endpoint => Default value is True. If True, includes the stop value else ignores it.

In [54]:
import numpy as np
 
print("Print Float Range Using NumPy LinSpace()\n")

print(np.linspace(1.0, 5.0, num = 5))
print(np.linspace(0, 10, num = 5, endpoint = False))

Print Float Range Using NumPy LinSpace()

[1. 2. 3. 4. 5.]
[0. 2. 4. 6. 8.]


### Генерация диапазона с плавающей запятой без использования сторонних модулей

In [ ]:
"""
Источник: https://dev-gang.ru/article/generacija-diapazona-s-plavausczei-zapjatoi-v-%E2%80%8B%E2%80%8Bpython-x3ad2eg0w7/

Desc : This function generates a float range of numbers w/o using any library.

Params :
A (int/float) : First number in the range
L (int/float) : Last number in the range
D (int/float) : Step or the common difference
"""
def float_range(A, L=None, D=None):
    #Use float number in range() function
    # if L and D argument is null set A=0.0 and D = 1.0
    if L == None:
        L = A + 0.0
        A = 0.0
    if D == None:
        D = 1.0
    while True:
        if D > 0 and A >= L:
            break
        elif D < 0 and A <= L:
            break
        yield ("%g" % A) # return float number
        A = A + D
#end of function float_range()

"""
Desc: This section calls the above function with different test data.
"""
print ("\nPrinting float range")
print ("\nTest 1: ", end = " ")
for i in float_range(0.1, 5.0, 0.5):
    print (i, end=", ")

print ("\nTest 2: ", end = " ")
for i in float_range(-5.0, 5.0, 1.5):
    print (i, end=", ")

print ("\nTest 3: ", end = " ")
for num in float_range(5.5):
    print (num, end=", ")

print ("\nTest 4: ", end = " ")
for num in float_range(10.1, 20.1):
    print (num, end=", ")

In [ ]:
import numpy as pynum_float
 
print(
  "Display range using a float value in the step\n", 
  pynum_float.arange(3, 33, 3.7)
)

## 5. Генераторы itertools <a name="itertools"></a>

Создать диапазон с плавающей запятой, используя Itertools

In [ ]:
from itertools import islice, count

def iter_range(start, stop, step):
    if step == 0:
        raise ValueError("Step could not be NULL")
    length = int(abs(stop - start) / step)
    return islice(count(start, step), length)

for it in iter_range(0, 10, 1.10):
    print ("{0:.1f}".format(it), end = " ")

itertools.count(start=0, step=1) - бесконечная арифметическая прогрессия с первым членом start и шагом step.

itertools.cycle(iterable) - возвращает по одному значению из последовательности, повторенной бесконечное число раз.

itertools.repeat(elem, n=Inf) - повторяет elem n раз.

itertools.accumulate(iterable) - аккумулирует суммы.

In [ ]:
import itertools

In [ ]:
itertools.accumulate([1, 2, 3, 4, 5])  # 1 3 6 10 15

In [ ]:
itertools.accumulate(range(1, 10))  # 1 3 6 10 15 21 28 36 45

itertools.chain(*iterables) - возвращает по одному элементу из первого итератора, потом из второго, до тех пор, пока итераторы не кончатся.

itertools.combinations(iterable, [r]) - комбинации длиной r из iterable без повторяющихся элементов.

In [ ]:
itertools.combinations('ABCD', 2)  # AB AC AD BC BD CD

itertools.combinations_with_replacement(iterable, r) - комбинации длиной r из iterable с повторяющимися элементами.

In [ ]:
itertools.combinations_with_replacement('ABCD', 2)  # AA AB AC AD BB BC BD CC CD DD

itertools.compress(data, selectors) - (d[0] if s[0]), (d[1] if s[1])

In [ ]:
itertools.compress('ABCDEF', [1,0,1,0,1,1])  # A C E F

itertools.dropwhile(func, iterable) - элементы iterable, начиная с первого, для которого func вернула ложь.

In [ ]:
itertools.dropwhile(lambda x: x < 5, [1,4,6,4,1])  # 6 4 1

itertools.filterfalse(func, iterable) - все элементы, для которых func возвращает ложь.

itertools.groupby(iterable, key=None) - группирует элементы по значению. Значение получается применением функции key к элементу (если аргумент key не указан, то значением является сам элемент).

In [55]:
from itertools import groupby

things = [('animal', 'bear'), ('animal', 'duck'), ('plant', 'cactus'), ('vehicle', 'speed boat'), ('vehicle', 'school bus')]

for key, group in groupby(things, lambda x: x[0]):
    for thing in group:
        print('A %s is a %s.' % (thing[1], key))
    print()

A bear is a animal.
A duck is a animal.

A cactus is a plant.

A speed boat is a vehicle.
A school bus is a vehicle.



itertools.islice(iterable[, start], stop[, step]) - итератор, состоящий из среза.

itertools.permutations(iterable, r=None) - перестановки длиной r из iterable.

itertools.product(*iterables, repeat=1) - аналог вложенных циклов.

In [ ]:
itertools.product('ABCD', 'xy')  # Ax Ay Bx By Cx Cy Dx Dy

itertools.starmap(function, iterable) - применяет функцию к каждому элементу последовательности (каждый элемент распаковывается).

In [ ]:
itertools.starmap(pow, [(2,5), (3,2), (10,3)])  # 32 9 1000

itertools.takewhile(func, iterable) - элементы до тех пор, пока func возвращает истину.

In [ ]:
itertools.takewhile(lambda x: x<5, [1,4,6,4,1])  # 1 4

itertools.tee(iterable, n=2) - кортеж из n итераторов.

itertools.zip_longest(*iterables, fillvalue=None) - как встроенная функция zip, но берет самый длинный итератор, а более короткие дополняет fillvalue.

In [ ]:
itertools.zip_longest('ABCD', 'xy', fillvalue='-')  # Ax By C- D-

## 6. Сопроцессы <a name="Coprocesses"></a>

Со-процессинг — это одновременное выполнение двух процедур, одна из которых считывает вывод другой.

## 7. Работа с файлами <a name="files"></a>

In [ ]:
f = open('text.txt', 'r')

'r' - открытие на чтение (является значением по умолчанию).  
'w' - открытие на запись, содержимое файла удаляется, если файла не существует, создается новый.  
'x' - открытие на запись, если файла не существует, иначе исключение.  
'a' - открытие на дозапись, информация добавляется в конец файла.  
'b' - открытие в двоичном режиме.  
't' - открытие в текстовом режиме (является значением по умолчанию).  
'+' - открытие на чтение и запись.  

'rb' - чтение в двоичном режиме. По умолчанию режим равен 'rt'.

In [ ]:
f.read(23)

In [ ]:
f.read()

In [ ]:
for line in f:
    print(line)

In [ ]:
l = [str(i)+str(i-1) for i in range(20)]

In [ ]:
f = open('text.txt', 'w')

In [ ]:
for index in l:
    f.write(index + '\n')

In [ ]:
f.close()

In [ ]:
f = open('text.txt', 'r')

In [ ]:
l = [line.strip() for line in f]
l

In [ ]:
f.close()